name: "Genshin Impact Helper"

on:
  workflow_dispatch:
  schedule:
    - cron: "15 22 * * 1"
    - cron: "23 23 * * 2"
    - cron: "48 22 * * 3"
    - cron: "43 23 * * 4"
    - cron: "10 22 * * 5"
    - cron: "11 23 * * 6"
    - cron: "18 22 * * 7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          pip install -r requirements.txt
          string="${{ secrets.COOKIE }}"
          IFS="#"
          array=($string)
          for var in ${array[@]}
          do
            python3 genshin.py <<EOF
            $var
          EOF
          done
